all: testAdd.bin testSub.bin testOr.bin testMul.bin testDiv.bin testMul8.bin testWat.bin testAnd.bin testJ1.bin testLAdd.bin bigOne.bin testAdd64.bin testMem.bin

clean:
	rm *.bin

testMem.bin:
	nasm -f bin -o testMem.bin testMem.asm

testAdd64.bin:
	nasm -f bin -o testAdd64.bin testAdd64.asm

bigOne.bin:
	nasm -f bin -o bigOne.bin bigOne.asm

testAdd.bin:
	nasm -f bin -o testAdd.bin testAdd.asm

testSub.bin:
	nasm -f bin -o testSub.bin testSub.asm

testOr.bin:
	nasm -f bin -o testOr.bin testOr.asm

testMul.bin:
	nasm -f bin -o testMul.bin testMul.asm

testMul8.bin:
	nasm -f bin -o testMul8.bin testMul8.asm

testDiv.bin:
	nasm -f bin -o testDiv.bin testDiv.asm

testWat.bin:
	nasm -f bin -o testWat.bin testWat.asm

testAnd.bin:
	nasm -f bin -o testAnd.bin testAnd.asm

testJ1.bin:
	nasm -f bin -o testJ1.bin testJ1.asm

testLAdd.bin:
	nasm -f bin -o testLAdd.bin testLAdd.asm
